version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-14-tools-deps-1.10.1.502-buster-node

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}-{{ checksum "deps.edn" }}

      - run: clojure -R:dev:clj-test:cljs-test -e "(prn :deps)"

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: v1-dependencies-{{ checksum "project.clj" }}-{{ checksum "deps.edn" }}

      - run: clojure -A:dev:clj-test
      - run: clojure -A:dev:cljs-test
