version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-11-tools-deps-1.10.1.754-buster-node

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}

      - run: clojure -M:dev:clj-test
      - run: clojure -M:dev:cljs-test -c '{:optimizations :advanced, :pseudo-names true}'

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: v1-dependencies-{{ checksum "deps.edn" }}
